### ISSUE TITLE
Windows Phone support

### ISSUE THREAD

**Issue by hypery2k** [holisticon/flynn-book-scanner#4]
Adding support for windows phone

**Comment by hypery2k** [comment]
see http://appfoundry.be/blog/2014/10/16/ionic-windows-phone/

**Comment by hypery2k** [comment]
Currently seeing errors:
```
'AgHost.exe' (CoreCLR: DefaultDomain): Loaded 'C:\windows\system32\mscorlib.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'AgHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.Windows.RuntimeHost.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'AgHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.Windows.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'AgHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.Net.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'AgHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'AgHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.Xml.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'AgHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\Data\Programs\{A3437850-A542-11E4-B1D5-F53A371496C7}\Install\de.holisticon.flynn.DLL'. Symbols loaded.
'AgHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\Microsoft.Phone.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'AgHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\Microsoft.Phone.Interop.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'AgHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\WinMetadata\Windows.winmd'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'AgHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.Xml.Linq.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'AgHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.Core.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Adding feature.value=Camera
Adding feature.value=DebugConsole
Adding feature.value=Device
Adding feature.value=Notification
'AgHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\en-US\mscorlib.debug.resources.dll'. Module was built without symbols.
A first chance exception of type 'System.IO.IsolatedStorage.IsolatedStorageException' occurred in mscorlib.ni.dll
Updating IsolatedStorage for APP:DeviceID :: 0a0c3701-a827-44eb-a626-e28fb1d9f967
CordovaBrowser_LoadCompleted
Apache Cordova native platform version 3.7.1 is starting
'AgHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.ServiceModel.Web.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'AgHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\System.Runtime.Serialization.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0xc64 has exited with code 259 (0x103).
CordovaBrowser_LoadCompleted
Apache Cordova native platform version 3.7.1 is starting
Error::Plugin not allowed in config.xml. Keyboard
Error::Plugin not allowed in config.xml. Keyboard
CordovaBrowser_LoadCompleted
Apache Cordova native platform version 3.7.1 is starting
Error::Plugin not allowed in config.xml. Keyboard
ERROR: Error during writing log entries: undefined
The thread 0xc8c has exited with code 259 (0x103).
ERROR: No log entries found
The thread 0xc90 has exited with code 259 (0x103).
CordovaBrowser_LoadCompleted
Apache Cordova native platform version 3.7.1 is starting
ERROR: Reading from local db not working: {"description":"Adapter is missing","code":404,"stack":"Error: Adapter is missing\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8980)\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8658)\n   at g (x-wmapp0:www/scripts/plugins.js:17:13652)\n   at c (x-wmapp0:www/scripts/plugins.js:17:13950)\n   at d (x-wmapp0:www/scripts/plugins.js:17:13668)\n   at c (x-wmapp0:www/scripts/plugins.js:17:11151)\n   at f (x-wmapp0:www/scripts/plugins.js:15:8542)\n   at g (x-wmapp0:www/scripts/app.js:1:19081)\n   at read (x-wmapp0:www/scripts/app.js:1:20706)\n   at j (x-wmapp0:www/scripts/app.js:1:13509)"}
The thread 0xca4 has exited with code 259 (0x103).
ERROR: Reading from local db not working: {"description":"Adapter is missing","code":404,"stack":"Error: Adapter is missing\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8980)\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8658)\n   at g (x-wmapp0:www/scripts/plugins.js:17:13652)\n   at c (x-wmapp0:www/scripts/plugins.js:17:13950)\n   at d (x-wmapp0:www/scripts/plugins.js:17:13668)\n   at c (x-wmapp0:www/scripts/plugins.js:17:11151)\n   at f (x-wmapp0:www/scripts/plugins.js:15:8542)\n   at g (x-wmapp0:www/scripts/app.js:1:19081)\n   at read (x-wmapp0:www/scripts/app.js:1:20706)\n   at j (x-wmapp0:www/scripts/app.js:1:13509)"}
The thread 0xca8 has exited with code 259 (0x103).
ERROR: Error during writing log entries: undefined
The thread 0xcb4 has exited with code 259 (0x103).
ERROR: No log entries found
The thread 0xcb8 has exited with code 259 (0x103).
ERROR: Reading from local db not working: {"description":"Adapter is missing","code":404,"stack":"Error: Adapter is missing\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8980)\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8658)\n   at g (x-wmapp0:www/scripts/plugins.js:17:13652)\n   at c (x-wmapp0:www/scripts/plugins.js:17:13950)\n   at d (x-wmapp0:www/scripts/plugins.js:17:13668)\n   at c (x-wmapp0:www/scripts/plugins.js:17:11151)\n   at f (x-wmapp0:www/scripts/plugins.js:15:8542)\n   at g (x-wmapp0:www/scripts/app.js:1:19081)\n   at read (x-wmapp0:www/scripts/app.js:1:20706)\n   at j (x-wmapp0:www/scripts/app.js:1:13509)"}
The thread 0xccc has exited with code 259 (0x103).
ERROR: Reading from local db not working: {"description":"Adapter is missing","code":404,"stack":"Error: Adapter is missing\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8980)\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8658)\n   at g (x-wmapp0:www/scripts/plugins.js:17:13652)\n   at c (x-wmapp0:www/scripts/plugins.js:17:13950)\n   at d (x-wmapp0:www/scripts/plugins.js:17:13668)\n   at c (x-wmapp0:www/scripts/plugins.js:17:11151)\n   at f (x-wmapp0:www/scripts/plugins.js:15:8542)\n   at g (x-wmapp0:www/scripts/app.js:1:19081)\n   at read (x-wmapp0:www/scripts/app.js:1:20706)\n   at j (x-wmapp0:www/scripts/app.js:1:13509)"}
The thread 0xcd0 has exited with code 259 (0x103).
The thread 0xbe8 has exited with code 259 (0x103).
CordovaBrowser_LoadCompleted
Apache Cordova native platform version 3.7.1 is starting
Error::Plugin not allowed in config.xml. Keyboard
Error::Plugin not allowed in config.xml. Keyboard
ERROR: Reading from local db not working: {"description":"Adapter is missing","code":404,"stack":"Error: Adapter is missing\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8980)\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8658)\n   at g (x-wmapp0:www/scripts/plugins.js:17:13652)\n   at c (x-wmapp0:www/scripts/plugins.js:17:13950)\n   at d (x-wmapp0:www/scripts/plugins.js:17:13668)\n   at c (x-wmapp0:www/scripts/plugins.js:17:11151)\n   at f (x-wmapp0:www/scripts/plugins.js:15:8542)\n   at g (x-wmapp0:www/scripts/app.js:1:19081)\n   at read (x-wmapp0:www/scripts/app.js:1:20706)\n   at l (x-wmapp0:www/scripts/app.js:1:5868)"}
The thread 0xcdc has exited with code 259 (0x103).
The thread 0xce0 has exited with code 259 (0x103).
CordovaBrowser_LoadCompleted
Apache Cordova native platform version 3.7.1 is starting
Error::Plugin not allowed in config.xml. Keyboard
ERROR: Reading from local db not working: {"description":"Adapter is missing","code":404,"stack":"Error: Adapter is missing\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8980)\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8658)\n   at g (x-wmapp0:www/scripts/plugins.js:17:13652)\n   at c (x-wmapp0:www/scripts/plugins.js:17:13950)\n   at d (x-wmapp0:www/scripts/plugins.js:17:13668)\n   at c (x-wmapp0:www/scripts/plugins.js:17:11151)\n   at f (x-wmapp0:www/scripts/plugins.js:15:8542)\n   at g (x-wmapp0:www/scripts/app.js:1:19081)\n   at read (x-wmapp0:www/scripts/app.js:1:20706)\n   at q (x-wmapp0:www/scripts/app.js:1:9288)"}
The thread 0xd10 has exited with code 259 (0x103).
ERROR: Error during reading inventory for search with critera {"keyword":"java"}:{}
The thread 0xd14 has exited with code 259 (0x103).
ERROR: Reading from local db not working: {"description":"Adapter is missing","code":404,"stack":"Error: Adapter is missing\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8980)\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8658)\n   at g (x-wmapp0:www/scripts/plugins.js:17:13652)\n   at c (x-wmapp0:www/scripts/plugins.js:17:13950)\n   at d (x-wmapp0:www/scripts/plugins.js:17:13668)\n   at c (x-wmapp0:www/scripts/plugins.js:17:11151)\n   at f (x-wmapp0:www/scripts/plugins.js:15:8542)\n   at g (x-wmapp0:www/scripts/app.js:1:19081)\n   at read (x-wmapp0:www/scripts/app.js:1:20706)\n   at q (x-wmapp0:www/scripts/app.js:1:9288)"}
The thread 0xd18 has exited with code 259 (0x103).
ERROR: Error during reading inventory for search with critera {"keyword":"java"}:{}
The thread 0xd1c has exited with code 259 (0x103).
ERROR: Reading from local db not working: {"description":"Adapter is missing","code":404,"stack":"Error: Adapter is missing\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8980)\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8658)\n   at g (x-wmapp0:www/scripts/plugins.js:17:13652)\n   at c (x-wmapp0:www/scripts/plugins.js:17:13950)\n   at d (x-wmapp0:www/scripts/plugins.js:17:13668)\n   at c (x-wmapp0:www/scripts/plugins.js:17:11151)\n   at f (x-wmapp0:www/scripts/plugins.js:15:8542)\n   at g (x-wmapp0:www/scripts/app.js:1:19081)\n   at read (x-wmapp0:www/scripts/app.js:1:20706)\n   at q (x-wmapp0:www/scripts/app.js:1:9288)"}
The thread 0xd20 has exited with code 259 (0x103).
ERROR: Error during reading inventory for search with critera {"keyword":"java"}:{}
The thread 0xd24 has exited with code 259 (0x103).
ERROR: Reading from local db not working: {"description":"Adapter is missing","code":404,"stack":"Error: Adapter is missing\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8980)\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8658)\n   at g (x-wmapp0:www/scripts/plugins.js:17:13652)\n   at c (x-wmapp0:www/scripts/plugins.js:17:13950)\n   at d (x-wmapp0:www/scripts/plugins.js:17:13668)\n   at c (x-wmapp0:www/scripts/plugins.js:17:11151)\n   at f (x-wmapp0:www/scripts/plugins.js:15:8542)\n   at g (x-wmapp0:www/scripts/app.js:1:19081)\n   at read (x-wmapp0:www/scripts/app.js:1:20706)\n   at q (x-wmapp0:www/scripts/app.js:1:9288)"}
The thread 0xd28 has exited with code 259 (0x103).
ERROR: Error during reading inventory for search with critera {"keyword":"java"}:{}
The thread 0xd2c has exited with code 259 (0x103).
The thread 0xbf0 has exited with code 259 (0x103).
ERROR: Reading from local db not working: {"description":"Adapter is missing","code":404,"stack":"Error: Adapter is missing\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8980)\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8658)\n   at g (x-wmapp0:www/scripts/plugins.js:17:13652)\n   at c (x-wmapp0:www/scripts/plugins.js:17:13950)\n   at d (x-wmapp0:www/scripts/plugins.js:17:13668)\n   at c (x-wmapp0:www/scripts/plugins.js:17:11151)\n   at f (x-wmapp0:www/scripts/plugins.js:15:8542)\n   at g (x-wmapp0:www/scripts/app.js:1:19081)\n   at read (x-wmapp0:www/scripts/app.js:1:20706)\n   at q (x-wmapp0:www/scripts/app.js:1:9288)"}
The thread 0xd34 has exited with code 259 (0x103).
ERROR: Error during reading inventory for search with critera {"keyword":"java"}:{}
The thread 0xd38 has exited with code 259 (0x103).
ERROR: Reading from local db not working: {"description":"Adapter is missing","code":404,"stack":"Error: Adapter is missing\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8980)\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8658)\n   at g (x-wmapp0:www/scripts/plugins.js:17:13652)\n   at c (x-wmapp0:www/scripts/plugins.js:17:13950)\n   at d (x-wmapp0:www/scripts/plugins.js:17:13668)\n   at c (x-wmapp0:www/scripts/plugins.js:17:11151)\n   at f (x-wmapp0:www/scripts/plugins.js:15:8542)\n   at g (x-wmapp0:www/scripts/app.js:1:19081)\n   at read (x-wmapp0:www/scripts/app.js:1:20706)\n   at q (x-wmapp0:www/scripts/app.js:1:9288)"}
The thread 0xd3c has exited with code 259 (0x103).
ERROR: Error during reading inventory for search with critera {"keyword":"java"}:{}
The thread 0xd40 has exited with code 259 (0x103).
ERROR: Reading from local db not working: {"description":"Adapter is missing","code":404,"stack":"Error: Adapter is missing\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8980)\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8658)\n   at g (x-wmapp0:www/scripts/plugins.js:17:13652)\n   at c (x-wmapp0:www/scripts/plugins.js:17:13950)\n   at d (x-wmapp0:www/scripts/plugins.js:17:13668)\n   at c (x-wmapp0:www/scripts/plugins.js:17:11151)\n   at f (x-wmapp0:www/scripts/plugins.js:15:8542)\n   at g (x-wmapp0:www/scripts/app.js:1:19081)\n   at read (x-wmapp0:www/scripts/app.js:1:20706)\n   at q (x-wmapp0:www/scripts/app.js:1:9288)"}
The thread 0xd44 has exited with code 259 (0x103).
ERROR: Error during reading inventory for search with critera {"keyword":"java"}:{}
The thread 0xd48 has exited with code 259 (0x103).
ERROR: Reading from local db not working: {"description":"Adapter is missing","code":404,"stack":"Error: Adapter is missing\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8980)\n   at Anonymous function (x-wmapp0:www/scripts/plugins.js:15:8658)\n   at g (x-wmapp0:www/scripts/plugins.js:17:13652)\n   at c (x-wmapp0:www/scripts/plugins.js:17:13950)\n   at d (x-wmapp0:www/scripts/plugins.js:17:13668)\n   at c (x-wmapp0:www/scripts/plugins.js:17:11151)\n   at f (x-wmapp0:www/scripts/plugins.js:15:8542)\n   at g (x-wmapp0:www/scripts/app.js:1:19081)\n   at read (x-wmapp0:www/scripts/app.js:1:20706)\n   at q (x-wmapp0:www/scripts/app.js:1:9288)"}
The thread 0xd4c has exited with code 259 (0x103).
ERROR: Error during reading inventory for search with critera {"keyword":"java"}:{}
The thread 0xd50 has exited with code 259 (0x103).
The thread 0xcd8 has exited with code 259 (0x103).
The thread 0xd84 has exited with code 259 (0x103).
```
